# -*- coding: utf-8 -*-
"""KlasterisasiTPAK2022.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1atPkwM6Hamz5cjO18TApGlU48Ih6joc2
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.preprocessing import MinMaxScaler

df = pd.read_csv('tingkatpekerjaan.csv')
df

df_x = df.iloc[:, 1:3]
df_x

plt.scatter(df.PendudukUsiaKerja, df.TPAK, s =10, c = "c", marker = "o", alpha = 1)
plt.xlabel('PendudukUsiaKerja')
plt.ylabel('TPAK')
plt.grid()

x_array =  np.array(df_x)
print(x_array)

scaler = MinMaxScaler()
x_scaled = scaler.fit_transform(x_array)
x_scaled

kmeans = KMeans(n_clusters = 3, random_state=123)
kmeans.fit(x_scaled)

print(kmeans.cluster_centers_)

print(kmeans.labels_)
df["tingkatpekerjaan"] = kmeans.labels_

df1 = df_x[df.tingkatpekerjaan==0]
df2 = df_x[df.tingkatpekerjaan==1]
df3 = df_x[df.tingkatpekerjaan==2]

plt.scatter(df1.PendudukUsiaKerja,df1['TPAK'],color='green')
plt.scatter(df2.PendudukUsiaKerja,df2['TPAK'],color='red')
plt.scatter(df3.PendudukUsiaKerja,df3['TPAK'],color='black')

plt.xlabel('PendudukUsiaKerja')
plt.ylabel('TPAK')
plt.grid()

output = plt.scatter(x_scaled[:,0], x_scaled[:,1], s = 100, c = df.tingkatpekerjaan, marker = "o", alpha = 1, )
centers = kmeans.cluster_centers_
plt.scatter(centers[:,0], centers[:,1], c='red', s=200, alpha=1 , marker="s");
plt.title("Hasil Klustering K-Means")
plt.colorbar (output)
plt.show()

conditions = [
    (df['tingkatpekerjaan']==0),
    (df['tingkatpekerjaan']==1),
    (df['tingkatpekerjaan']==2)]
choices = ['Rata-rata','Rendah','Tinggi']
df['tingkatpekerjaan'] = np.select(conditions, choices)
df